routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\AuditController;
use Illuminate\Support\Facades\Artisan;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/linkmigrate', function () {
    Artisan::call('migrate');
});
Route::get('/linkstorage', function () {
    Artisan::call('storage:link');
});

Route::get('audits', 'App\Http\Controllers\AuditController@index')
    ->middleware('auth', \App\Http\Middleware\AllowOnlyAdmin::class)->name('audits');

Route::group(['middleware' => ['auth']], function () {
    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
    Route::resource('roles', RoleController::class);
    Route::resource('users', UserController::class);
    Route::resource('companies', 'App\Http\Controllers\CompanyController'::class);
    Route::resource('employees', 'App\Http\Controllers\EmployeeController'::class);
});

app/Models/company.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use App\Models\employee;
use Illuminate\Database\Eloquent\SoftDeletes;
use OwenIt\Auditing\Contracts\Auditable;

class company extends Model implements Auditable
{
    use HasFactory, SoftDeletes, \OwenIt\Auditing\Auditable;


    protected $fillable = [
        'name', 'email', 'logo', 'website', 'user_id'
    ];

    public function employees()
    {
        return $this->hasMany('App\Models\employee', 'company_id', 'id');
    }
}

app/Http/Controllers/CompanyController.php
<?php

namespace App\Http\Controllers;

use App\Models\company;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\Models\User;
use App\Models\employee;
use Spatie\Permission\Models\Role;
use DB;
use Facade\FlareClient\Stacktrace\File;
use Hash;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Str;
use Mailgun\Mailgun;




class CompanyController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    function __construct()
    {
        $this->middleware('permission:company-list|company-create|company-edit|company-delete', ['only' => ['index', 'show']]);
        $this->middleware('permission:company-create', ['only' => ['create', 'store']]);
        $this->middleware('permission:company-edit', ['only' => ['edit', 'update']]);
        $this->middleware('permission:company-delete', ['only' => ['destroy']]);
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        if (Auth::user()->roles()->where('name', 'employee')->exists()) {
            $employee = DB::table('employees')->where('user_id', Auth::user()->id)->first();
            $company = DB::table('companies')->where('id', $employee->company_id)->first();
            return view('companies.show', compact('company'));
        }
        if (Auth::user()->roles()->where('name', 'company')->exists()) {
            $company = DB::table('companies')->where('user_id', Auth::user()->id)->first(); //company::where('user_id', Auth::user()->id)->first();;
            return view('companies.show')->with('company', $company);
        }

        $companies = company::with('employees')->latest()->paginate(5);
        return view('companies.index', compact('companies'))
            ->with('i', (request()->input('page', 1) - 1) * 5);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        return view('companies.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        request()->validate([
            'name' => 'required',
            'email' => 'required',
        ]);

        $password = Str::random(8) . "@" . Str::random(2);

        $input = $request->all();
        $user = User::create([
            'name' => $input['name'],
            'email' => $input['email'],
            'password' => Hash::make($password) // bcrypt('password')
        ]);
        $role = Role::where('name', '=', 'company')->pluck('id', 'id')->all();
        $user->assignRole($role);


        $storeImageName = "";
        if ($request->file('logoFile') != null) {
            $storeName = $request->file('logoFile')->store('public');
            $storeImageName = str_ireplace("public/", "", $storeName);
        }

        $user = company::create([
            'name' => $input['name'],
            'email' => $input['email'],
            'website' => $input['website'],
            'logo' => $storeImageName,
            'user_id' => $user->id
        ]);

        $toEmail = $input['email'];
        $mailBody = 'Hi ' . $input['name'] . ',' . '<br/><br/>Please note that a Glade Test Account was created for you successfuly! please find your login detail below<br/><br/>User Name:<b>' . $input['email'] . '</b><br/>Passord:<b>' . $password . '</b><br/><br/><br/>Thank You.';

        Mail::html($mailBody, function ($message) use ($toEmail) {
            $message->subject('Glade Test Account Creation!');
            $message->from('no-reply@gladetest.com', config('app.name', 'Laravel'));
            $message->to(env('APP_EMAIL_TEST', $toEmail));
        });

        var_dump(Mail::failures());

        return redirect()->route('companies.index')
            ->with('success', 'company created successfully.');
    }



    /**
     * Display the specified resource.
     *
     * @param  \App\company  $company
     * @return \Illuminate\Http\Response
     */
    public function show(company $company)
    {
        return view('companies.show', compact('company'));
    }



    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\company  $company
     * @return \Illuminate\Http\Response
     */
    public function edit(company $company)
    {
        return view('companies.edit', compact('company'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\company  $company
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, company $company)
    {


        request()->validate([
            'name' => 'required',
            'email' => 'required',
        ]);

        $input = $request->all();
        $storeImageName = $company->logo;

        if ($request->file('logoFile') != null) {

            $storeName = $request->file('logoFile')->store('public');
            $storeImageName = str_ireplace("public/", "", $storeName);

            $path = public_path("storage/$company->logo");
            if (is_file($path)) {
                unlink($path);
            }
        }


        $company->update([
            'name' => $input['name'],
            'email' => $input['email'],
            'website' => $input['website'],
            'logo' => $storeImageName
        ]);

        $user = user::where('id', $company->user_id)->first();

        $user->update([
            'name' => $input['name'],
            'email' => $input['email'],
        ]);



        return redirect()->route('companies.index')
            ->with('success', 'company updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\company  $company
     * @return \Illuminate\Http\Response
     */
    public function destroy(company $company)
    {
        user::where('id', $company->user_id)->delete();

        return redirect()->route('companies.index')
            ->with('success', 'company deleted successfully');
    }
}

resources/views/companies/create.blade.php
@extends('layouts.app')


@section('content')
<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2>Add New company</h2>
        </div>
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ route('companies.index') }}"> Back</a>
        </div>
    </div>
</div>


@if ($errors->any())
<div class="alert alert-danger">
    <strong>Whoops!</strong> There were some problems with your input.<br><br>
    <ul>
        @foreach ($errors->all() as $error)
        <li>{{ $error }}</li>
        @endforeach
    </ul>
</div>
@endif


<form action="{{ route('companies.store') }}" method="POST" enctype="multipart/form-data">
    @csrf


    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-6">
            <div class="form-group">
                <strong>Name:</strong>
                <input type="text" name="name" required class="form-control" placeholder="Name">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-6">
            <div class="form-group">
                <strong>Email:</strong>
                <input type="email" class="form-control" required name="email" placeholder="Email"></input>
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-6">
            <div class="form-group">
                <strong>Website:</strong>
                <input type="website" class="form-control" name="website" placeholder="Website"></input>
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-6">
            <div class="form-group">
                <strong>Logo:</strong>
                <input type="file" id="logoFile" class="form-control" name="logoFile"></input>
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </div>


</form>

@endsection

resources/views/companies/edit.blade.php
@extends('layouts.app')


@section('content')
<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2>Edit company</h2>
        </div>
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ route('companies.index') }}"> Back</a>
        </div>
    </div>
</div>


@if ($errors->any())
<div class="alert alert-danger">
    <strong>Whoops!</strong> There were some problems with your input.<br><br>
    <ul>
        @foreach ($errors->all() as $error)
        <li>{{ $error }}</li>
        @endforeach
    </ul>
</div>
@endif


<form action="{{ route('companies.update',$company->id) }}" method="POST" enctype="multipart/form-data">
    @csrf
    @method('PUT')


    <div class="row">


        <div class="col-xs-12 col-sm-12 col-md-6">
            <div class="form-group">
                <strong>Name:</strong>
                <input type="text" name="name" value="{{ $company->name }}" required class="form-control"
                    placeholder="Name">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-6">
            <div class="form-group">
                <strong>Email:</strong>
                <input type="email" value="{{ $company->email }}" class="form-control" required name="email"
                    placeholder="Email"></input>
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-6">
            <div class="form-group">
                <strong>Website:</strong>
                <input type="website" value="{{ $company->website }}" class="form-control" name="website"
                    placeholder="Website"></input>
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-6">
            <div class="form-group">
                <strong>Logo:</strong>
                <input type="file" id="logoFile" class="form-control" name="logoFile"></input>
            </div>
            <img src="{{ URL::asset('storage/'.$company->logo) }}" width=100 class="pull-right img-thumbnail" />
        </div>

        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </div>


</form>


@endsection

resources/views/companies/index.blade.php
@extends('layouts.app')


@section('content')
<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2>companies</h2>
        </div>
        <div class="pull-right">
            @can('company-create')
            <a class="btn btn-success" href="{{ route('companies.create') }}"> Create New company</a>
            @endcan
        </div>
    </div>
</div>


@if ($message = Session::get('success'))
<div class="alert alert-success">
    <p>{{ $message }}</p>
</div>
@endif


<table class="table table-bordered">
    <tr>
        <th>No</th>
        <th>Name</th>
        <th>Email</th>
        <th>Website</th>
        <th>Employees Count</th>
        <th width="280px">Action</th>
    </tr>
    @foreach ($companies as $company)
    <tr>
        <td>{{ ++$i }}</td>
        <td>{{ $company->name }}</td>
        <td>{{ $company->email }}</td>
        <td>{{ $company->website }}</td>
        <td>{{ $company->employees->count() }}</td>
        <td>
            <form action="{{ route('companies.destroy',$company->id) }}" method="POST">
                <a class="btn btn-info" href="{{ route('companies.show',$company->id) }}">Show</a>
                @can('company-edit')
                <a class="btn btn-primary" href="{{ route('companies.edit',$company->id) }}">Edit</a>
                @endcan


                @csrf
                @method('DELETE')
                @can('company-delete')
                <button type="submit" class="btn btn-danger">Delete</button>
                @endcan
            </form>
        </td>
    </tr>
    @endforeach
</table>


{!! $companies->links() !!}



@endsection

resources/views/companies/show.blade.php
@extends('layouts.app')


@section('content')

<div class="row">
    <div class="col-lg-12 margin-tb">

        @if(Auth::user()->roles()->where('name', 'superadmin')->exists() || Auth::user()->roles()->where('name',
        'admin')->exists())
        <span class="pull-right" style="float: right;">
            <a class="btn btn-primary" href="{{ route('companies.index') }}"> Back</a>
        </span>
        @endif

        @if(Auth::user()->roles()->where('name', 'company')->exists())
        <span class="pull-right" style="float: right;">
            <a class="btn btn-primary" href="{{ route('companies.edit', $company->id) }}"> Edit</a>
        </span>
        @endif

        <div class="pull-left">
            <h2> {{ $company->name }} Detail</h2>
        </div>
    </div>
</div>


<div class="row">
    <div class="col-xs-12 col-sm-12 col-md-6">
        <div class="form-group">
            <strong>Name:</strong>
            {{ $company->name }}
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-6">
        <div class="form-group">
            <strong>Email:</strong>
            {{ $company->email }}
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-6">
        <div class="form-group">
            <strong>Web Site:</strong>
            {{ $company->website }}
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-6">
        <div class="form-group">
            <strong>Logo:</strong><br />
            <img src="{{ URL::asset('storage/'.$company->logo) }}" width=100 class="img-thumbnail" />
        </div>
    </div>
</div>
@endsection