routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\AuditController;
use Illuminate\Support\Facades\Artisan;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/linkmigrate', function () {
    Artisan::call('migrate');
});
Route::get('/linkstorage', function () {
    Artisan::call('storage:link');
});

Route::get('audits', 'App\Http\Controllers\AuditController@index')
    ->middleware('auth', \App\Http\Middleware\AllowOnlyAdmin::class)->name('audits');

Route::group(['middleware' => ['auth']], function () {
    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
    Route::resource('roles', RoleController::class);
    Route::resource('users', UserController::class);
    Route::resource('companies', 'App\Http\Controllers\CompanyController'::class);
    Route::resource('employees', 'App\Http\Controllers\EmployeeController'::class);
});

app/Models/employee.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use OwenIt\Auditing\Contracts\Auditable;

class employee extends Model implements Auditable
{
    use HasFactory, SoftDeletes, \OwenIt\Auditing\Auditable;

    protected $fillable = [
        'firstName', 'lastName', 'email', 'phone', 'user_id', 'company_id'
    ];

    public function company()
    {
        return $this->hasOne('App\Models\company',  'id', 'company_id');
    }
}

app/Http/Controllers/EmployeeController.php
<?php

namespace App\Http\Controllers;

use App\Models\company;
use App\Models\employee;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

use App\Models\User;
use Spatie\Permission\Models\Role;
use DB;
use Hash;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Str;
use Mailgun\Mailgun;

class EmployeeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    function __construct()
    {
        $this->middleware('permission:employee-list|employee-create|employee-edit|employee-delete', ['only' => ['index', 'show']]);
        $this->middleware('permission:employee-create', ['only' => ['create', 'store']]);
        $this->middleware('permission:employee-edit', ['only' => ['edit', 'update']]);
        $this->middleware('permission:employee-delete', ['only' => ['destroy']]);
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        if (Auth::user()->roles()->where('name', 'employee')->exists()) {
            $employee = DB::table('employees')->where('user_id', Auth::user()->id)->first();
            return view('employees.show', compact('employee'));
        }
        if (Auth::user()->roles()->where('name', 'company')->exists()) {
            $company = company::with(['employees'])->where('user_id', Auth::user()->id)->first();
            //$company->dd();
            ///$employees = $company->employees->all();
            $employees = employee::with(['company'])->where('company_id', '=', $company->id)->latest()->paginate(5);
        }
        if (
            Auth::user()->roles()->where('name', 'superadmin')->exists() ||
            Auth::user()->roles()->where('name', 'admin')->exists()
        ) {
            $employees = employee::latest()->paginate(5);
        }
        return view('employees.index', compact('employees'))
            ->with('i', (request()->input('page', 1) - 1) * 5);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

        if (Auth::user()->roles()->where('name', 'admin')->exists() || Auth::user()->roles()->where('name', 'superadmin')->exists()) {
            $company = company::get();
        }
        if (Auth::user()->roles()->where('name', 'company')->exists()) {
            $company = company::where('user_id', '=', Auth::user()->id)->first();
        }
        return view('employees.create', compact('company'));
        // return view('employees.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        request()->validate([
            'firstName' => 'required',
            'company_id' => 'required',
            'email' => 'required',
        ]);

        $input = $request->all();
        $password = Str::random(8) . "@" . Str::random(2);
        $user = User::create([
            'name' => $input['firstName'] . " " . $input['lastName'],
            'email' => $input['email'],
            'password' => Hash::make($password) // bcrypt('password')
        ]);
        $role = Role::where('name', '=', 'employee')->pluck('id', 'id')->all();
        $user->assignRole($role);


        $user = employee::create([
            'firstName' => $input['firstName'],
            'lastName' => $input['lastName'],
            'email' => $input['email'],
            'company_id' => $input['company_id'],
            'phone' => $input['phone'],
            'user_id' => $user->id
        ]);

        $toEmail = $input['email'];
        $mailBody = 'Hi ' . $input['firstName'] . ',' . '<br/><br/>Please note that a Glade Test Account was created for you successfuly! please find your login detail below<br/><br/>User Name:<b>' . $input['email'] . '</b><br/>Passord:<b>' . $password . '</b><br/><br/><br/>Thank You.';

        Mail::html($mailBody, function ($message) use ($toEmail) {
            $message->subject('Glade Test Account Creation!');
            $message->from('no-reply@gladetest.com', config('app.name', 'Laravel'));
            $message->to(env('APP_EMAIL_TEST', $toEmail));
        });

        var_dump(Mail::failures());

        return redirect()->route('employees.index')
            ->with('success', 'Employee created successfully.');
    }




    /**
     * Display the specified resource.
     *
     * @param  \App\employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function show(employee $employee)
    {
        return view('employees.show', compact('employee'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function edit(employee $employee)
    {
        if (Auth::user()->roles()->where('name', 'admin')->exists() || Auth::user()->roles()->where('name', 'superadmin')->exists()) {
            $company = company::get();
        }
        if (Auth::user()->roles()->where('name', 'company')->exists()) {
            $company = company::where('user_id', '=', Auth::user()->id)->first();
        }
        if (Auth::user()->roles()->where('name', 'employee')->exists()) {
            $company = company::where('id', '=', $employee->company_id)->first();
        }
        return view('employees.edit', compact('employee'))->with('company', $company);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, employee $employee)
    {
        request()->validate([
            'firstName' => 'required',
            'company_id' => 'required',
            'email' => 'required',
        ]);
        $input = $request->all();
        $employee->update([
            'firstName' => $input['firstName'],
            'lastName' => $input['lastName'],
            'email' => $input['email'],
            'company_id' => $input['company_id'],
            'phone' => $input['phone']
        ]);

        $User = user::where('id', $employee->user_id)->first();

        $User->update([
            'name' => $input['firstName'] . " " . $input['lastName'],
            'email' => $input['email']
        ]);


        return redirect()->route('employees.index')
            ->with('success', 'employee updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function destroy(employee $employee)
    {

        user::where('id', $employee->user_id)->delete();

        return redirect()->route('employees.index')
            ->with('success', 'employee deleted successfully');
    }
}

resources/views/employees/create.blade.php
@extends('layouts.app')


@section('content')
<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2>Add New employee</h2>
        </div>
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ route('employees.index') }}"> Back</a>
        </div>
    </div>
</div>


@if ($errors->any())
<div class="alert alert-danger">
    <strong>Whoops!</strong> There were some problems with your input.<br><br>
    <ul>
        @foreach ($errors->all() as $error)
        <li>{{ $error }}</li>
        @endforeach
    </ul>
</div>
@endif


<form action="{{ route('employees.store') }}" method="POST">
    @csrf


    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-6">
            <div class="form-group">
                <strong>First Name:</strong>
                <input type="text" required name="firstName" class="form-control" placeholder="First Name">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-6">
            <div class="form-group">
                <strong>Last Name:</strong>
                <input type="text" name="lastName" class="form-control" placeholder="Last Name">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-6">
            <div class="form-group">
                <strong>Email:</strong>
                <input type="email" name="email" required class="form-control" placeholder="Email">
            </div>
        </div>



        <div class="col-xs-12 col-sm-12 col-md-6">
            <div class="form-group">
                <strong>Phone Number:</strong>
                <input type="text" name="phone" class="form-control" placeholder="Phone Number">
            </div>
        </div>

        @if(Auth::user()->roles()->where('name', 'company')->exists() )
        <input type="hidden" name="company_id" required value="{{ $company->id }}">
        @endif

        @if(Auth::user()->roles()->where('name', 'admin')->exists() || Auth::user()->roles()->where('name',
        'superadmin')->exists() )
        <div class="col-xs-12 col-sm-12 col-md-6">
            <div class="form-group">
                <strong>Company:</strong>
                <select name="company_id" class="form-control" id="company_id" required>
                    <option value=""></option>
                    @foreach($company as $display)
                    <option value="{{ $display->id }}">{{ $display->name }}</option>
                    @endforeach
                </select>
            </div>
        </div>
        @endif
        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </div>


</form>

@endsection

resources/views/employees/edit.blade.php
@extends('layouts.app')


@section('content')
<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2>Edit Employee</h2>
        </div>
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ route('employees.index') }}"> Back</a>
        </div>
    </div>
</div>


@if ($errors->any())
<div class="alert alert-danger">
    <strong>Whoops!</strong> There were some problems with your input.<br><br>
    <ul>
        @foreach ($errors->all() as $error)
        <li>{{ $error }}</li>
        @endforeach
    </ul>
</div>
@endif


<form action="{{ route('employees.update',$employee->id) }}" method="POST">
    @csrf
    @method('PUT')


    <div class="row">


        <div class="col-xs-12 col-sm-12 col-md-6">
            <div class="form-group">
                <strong>First Name:</strong>
                <input type="text" name="firstName" value="{{ $employee->firstName }}" class="form-control"
                    placeholder="First Name">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-6">
            <div class="form-group">
                <strong>Last Name:</strong>
                <input type="text" name="lastName" value="{{ $employee->lastName }}" class="form-control"
                    placeholder="Last Name">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-6">
            <div class="form-group">
                <strong>Email:</strong>
                <input type="email" name="email" value="{{ $employee->email }}" required class="form-control"
                    placeholder="Email">
            </div>
        </div>

        <div class="col-xs-12 col-sm-12 col-md-6">
            <div class="form-group">
                <strong>Phone Number:</strong>
                <input type="text" name="phone" value="{{ $employee->phone }}" class="form-control"
                    placeholder="Phone Number">
            </div>
        </div>

        @if(Auth::user()->roles()->where('name', 'company')->exists()||Auth::user()->roles()->where('name',
        'employee')->exists() )
        <input type="hidden" name="company_id" required value="{{ $company->id }}">
        @endif

        @if(Auth::user()->roles()->where('name', 'admin')->exists() || Auth::user()->roles()->where('name',
        'superadmin')->exists() )
        <div class="col-xs-12 col-sm-12 col-md-6">
            <div class="form-group">
                <strong>Company:</strong>
                <select name="company_id" class="form-control" id="company_id" required>
                    <option value=""></option>

                    <option value=""></option>
                    @foreach($company as $display)
                    @if($display->id == $employee->company_id)
                    <option selected value="{{ $display->id }}">{{ $display->name }}</option>
                    @else
                    <option value="{{ $display->id }}">{{ $display->name }}</option>
                    @endif



                    @endforeach




                </select>
            </div>
        </div>
        @endif






        {{--
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Name:</strong>
                <input type="text" name="name" value="{{ $employee->name }}" class="form-control" placeholder="Name">
    </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Detail:</strong>
            <textarea class="form-control" style="height:150px" name="detail"
                placeholder="Detail">{{ $employee->detail }}</textarea>
        </div>
    </div> --}}
    <div class="col-xs-12 col-sm-12 col-md-12 text-center">
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>
    </div>


</form>


@endsection

resources/views/employees/index.blade.php
@extends('layouts.app')


@section('content')
<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2>employees</h2>
        </div>
        <div class="pull-right">
            @can('employee-create')
            <a class="btn btn-success" href="{{ route('employees.create') }}"> Create New employee</a>
            @endcan
        </div>
    </div>
</div>


@if ($message = Session::get('success'))
<div class="alert alert-success">
    <p>{{ $message }}</p>
</div>
@endif


<table class="table table-bordered">
    <tr>
        <th>No</th>
        <th>Name</th>
        <th>Email</th>
        <th>Phone Number</th>
        <th>Company</th>
        <th width="280px">Action</th>
    </tr>
    @foreach ($employees as $employee)
    <tr>
        <td>{{ ++$i }}</td>
        <td>{{ $employee->firstName  }} {{ $employee->lastName }}</td>
        <td>{{ $employee->email }}</td>
        <td>{{ $employee->phone }}</td>
        <td>{{ $employee->company->name }}</td>
        <td>
            <form action="{{ route('employees.destroy',$employee->id) }}" method="POST">
                <a class="btn btn-info" href="{{ route('employees.show',$employee->id) }}">Show</a>
                @can('employee-edit')
                <a class="btn btn-primary" href="{{ route('employees.edit',$employee->id) }}">Edit</a>
                @endcan


                @csrf
                @method('DELETE')
                @can('employee-delete')
                <button type="submit" class="btn btn-danger">Delete</button>
                @endcan
            </form>
        </td>
    </tr>
    @endforeach
</table>


{!! $employees->links() !!}



@endsection

resources/views/employees/show.blade.php
@extends('layouts.app')


@section('content')
<div class="row">
    <div class="col-lg-12 margin-tb">

        @if(Auth::user()->roles()->where('name', 'superadmin')->exists() || Auth::user()->roles()->where('name',
        'admin')->exists()|| Auth::user()->roles()->where('name',
        'company')->exists())
        <span class="pull-right" style="float: right;">
            <a class="btn btn-primary" href="{{ route('employees.index') }}"> Back</a>
        </span>
        @endif

        @if(Auth::user()->roles()->where('name', 'employee')->exists())
        <span class="pull-right" style="float: right;">
            <a class="btn btn-primary" href="{{ route('employees.edit', $employee->id) }}"> Edit</a>
        </span>
        @endif

        <div class="pull-left">
            <h2> {{ $employee->firstName." ".$employee->lastName }} Detail</h2>
        </div>



    </div>
</div>


<div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Name:</strong>
            {{ $employee->firstName }}
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Details:</strong>
            {{ $employee->lastName }}
        </div>
    </div>
</div>
@endsection